'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {LanguageSwitch,useLocale} from '@/modules/localization/ui/provider';
import {type ProviderPage,type Offering,providerRoles,mediaUrl} from '../application/catalog';
import {Visual} from './visual';
export default function Directory(){const {t,locale}=useLocale();const [pages,setPages]=useState<ProviderPage[]>([]);const [offers,setOffers]=useState<Offering[]>([]);const [role,setRole]=useState('');const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all([supabase.from('provider_pages').select('*').eq('status','PUBLISHED').order('created_at',{ascending:false}).limit(200),supabase.from('provider_offerings').select('*').eq('status','ACTIVE').order('created_at',{ascending:false}).limit(400)]).then(([p,o])=>{if(!active)return;if(p.error||o.error)setError(t('error'));else{setPages(p.data||[]);setOffers(o.data||[]);}setLoading(false);}).catch(()=>{if(active){setError(t('error'));setLoading(false);}});return()=>{active=false;};},[retry]);
 const visible=pages.filter(p=>(!role||p.role===role)&&`${p.display_name} ${p.city} ${p.headline} ${offers.filter(o=>o.provider_id===p.id).map(o=>o.title).join(' ')}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 return <div className="public-site"><header className="public-nav"><a href="/" className="brand">CUE<span>LANCE</span></a><nav><a href="/workspace">{t('page.dashboard')}</a><LanguageSwitch/></nav></header><main className="public-body"><section className="directory-intro"><p className="eyebrow">CUELANCE / {t('page.marketplace')}</p><h1>{t('page.providers')}</h1><p>{t('page.tagline')}</p></section><div className="directory-filters"><label>{t('search')}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>{t('page.kind')}<select value={role} onChange={e=>setRole(e.target.value)}><option value="">{t('page.all')}</option>{providerRoles.map(r=><option key={r} value={r}>{t(`page.${r}`)}</option>)}</select></label></div>
 {loading?<p role="status">{t('loading')}</p>:error?<div role="alert"><p>{error}</p><button className="button" onClick={()=>setRetry(x=>x+1)}>{t('refresh')}</button></div>:<><section className="visual-grid">{visible.map(p=><a className="visual-card" key={p.id} href={`/p/${p.slug}`}><Visual src={mediaUrl(p.cover_asset_id)} alt={p.display_name}/><div className="visual-card-body"><span className="eyebrow">{t(`page.${p.role}`)} · {p.city}</span><h2>{p.display_name}</h2><p>{p.headline}</p><span className="text-link">{t('page.profile')} ↗</span></div></a>)}</section>{!visible.length&&<p>{t('page.empty')}</p>}<h2 className="section-heading">{t('page.offerings')}</h2><section className="visual-grid">{offers.filter(o=>visible.some(p=>p.id===o.provider_id)).map(o=>{const p=pages.find(p=>p.id===o.provider_id)!;return <a className="visual-card" key={o.id} href={`/p/${p.slug}#inquiry`}><Visual src={mediaUrl(o.image_asset_id||p.cover_asset_id)} alt={o.title}/><div className="visual-card-body"><small>{p.display_name}</small><h3>{o.title}</h3><p>{o.description}</p><b>{t('page.from')} {new Intl.NumberFormat(locale,{style:'currency',currency:o.currency}).format(o.price)}</b></div></a>;})}</section></>}
 </main></div>;
}
