'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useLocale} from '@/modules/localization/ui/provider';
import {ModuleHeading,GuidedField,Status} from '@/modules/ui/guided';
import {type ProviderPage,type ProviderRole,type Offering} from '../application/catalog';
import ImageInput from './image-input';
const blank={display_name:'',slug:'',headline:'',bio:'',city:'',website:'',cover_asset_id:null as string|null,avatar_asset_id:null as string|null,status:'DRAFT'};
const blankOffering={title:'',description:'',kind:'SERVICE',price:0,currency:'SAR',image_asset_id:null as string|null,status:'DRAFT'};
type Inquiry={id:string;message:string;status:string;created_at:string;reply:string};
export default function ProviderEditor({role}:{role:ProviderRole}){
 const {t}=useLocale();const [page,setPage]=useState<ProviderPage|null>(null);const [form,setForm]=useState(blank);const [offer,setOffer]=useState(blankOffering);const [editId,setEditId]=useState<string|null>(null);const [offers,setOffers]=useState<Offering[]>([]);const [inquiries,setInquiries]=useState<Inquiry[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [dirty,setDirty]=useState(false);const [draftKey,setDraftKey]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');setPage(null);setForm(blank);setOffers([]);setInquiries([]);setDirty(false);
 (async()=>{try{const {data}=await supabase.auth.getUser();if(!data.user)throw new Error(t('signin'));const key=`cuelance.page-draft.${data.user.id}.${role}`;if(active)setDraftKey(key);const result=await supabase.from('provider_pages').select('*').eq('owner_user_id',data.user.id).eq('role',role).maybeSingle();if(result.error)throw result.error;if(!active)return;if(result.data){setPage(result.data);setForm(result.data);const [o,i]=await Promise.all([supabase.from('provider_offerings').select('*').eq('provider_id',result.data.id).order('created_at',{ascending:false}),supabase.from('provider_inquiries').select('id,message,status,created_at,reply').eq('provider_id',result.data.id).order('created_at',{ascending:false})]);if(o.error)throw o.error;if(i.error)throw i.error;if(active){setOffers(o.data||[]);setInquiries(i.data||[]);}}if(active){try{const cached=sessionStorage.getItem(key);if(cached){setForm(JSON.parse(cached));setDirty(true);}}catch{}}}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[role]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 useEffect(()=>{if(dirty&&draftKey)sessionStorage.setItem(draftKey,JSON.stringify(form));},[form,dirty,draftKey]);
 function change(key:keyof typeof blank,value:string|null){setDirty(true);setForm(x=>({...x,[key]:value}));}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work();setNotice(t('saved'));}catch(e){setError((e as Error).message);void supabase.rpc('record_operational_log',{p_level:'ERROR',p_area:'provider_pages',p_message:'Provider operation failed',p_context:{role},p_request_path:'/workspace'});}finally{setBusy(false);}}
 async function save(status:string){await run(async()=>{const {data}=await supabase.auth.getUser();if(!data.user)throw new Error(t('signin'));const payload={...Object.fromEntries(Object.keys(blank).map(k=>[k,form[k as keyof typeof blank]])),status,owner_user_id:data.user.id,role};const result=page?await supabase.from('provider_pages').update(payload).eq('id',page.id).select().single():await supabase.from('provider_pages').insert(payload).select().single();if(result.error)throw result.error;setPage(result.data);setForm(result.data);setDirty(false);if(draftKey)sessionStorage.removeItem(draftKey);});}
 async function saveOffer(){if(!page)return;await run(async()=>{const payload={...offer,provider_id:page.id,price:Number(offer.price)};const result=editId?await supabase.from('provider_offerings').update(payload).eq('id',editId).select().single():await supabase.from('provider_offerings').insert(payload).select().single();if(result.error)throw result.error;setOffers(x=>[result.data,...x.filter(o=>o.id!==result.data.id)]);setOffer(blankOffering);setEditId(null);});}
 if(loading)return <p role="status">{t('loading')}</p>;
 return <><ModuleHeading title={t('page.title')} help={t('page.help')}/><Status text={error} error/><Status text={notice}/><div className="provider-editor"><form className="card module-form" onSubmit={e=>{e.preventDefault();void save(form.status);}}>
 <p className="eyebrow">{t(`page.${role}`)}</p>
 {(['display_name','slug','headline','city','website'] as const).map(k=><GuidedField key={k} label={t(({display_name:'page.name',slug:'page.slug',headline:'page.headline',city:'page.city',website:'page.website'} as const)[k])} help={k==='slug'?t('page.slugHelp'):t('page.help')}><input required={k==='display_name'||k==='slug'} value={form[k]} type={k==='website'?'url':'text'} maxLength={k==='slug'?70:k==='headline'?180:120} pattern={k==='slug'?'[a-z0-9][a-z0-9-]{2,69}':undefined} onChange={e=>change(k,e.target.value)}/></GuidedField>)}
 <GuidedField label={t('page.bio')} help={t('page.help')}><textarea rows={6} maxLength={6000} value={form.bio} onChange={e=>change('bio',e.target.value)}/></GuidedField>
 <div className="actions"><button className="button primary" disabled={busy}>{t('save')}</button><button type="button" className="button" disabled={busy} onClick={()=>save('PUBLISHED')}>{t('page.publish')}</button>{page?.status==='PUBLISHED'&&<button className="button" type="button" disabled={busy} onClick={()=>save('PAUSED')}>{t('page.pause')}</button>}</div>
 {page?.status==='PUBLISHED'&&<a className="button" href={`/p/${page.slug}`} target="_blank" rel="noopener">{t('page.open')} ↗</a>}
 </form><aside className="card module-form"><ImageInput label={t('page.cover')} value={form.cover_asset_id} onChange={id=>change('cover_asset_id',id)}/><ImageInput label={t('page.avatar')} value={form.avatar_asset_id} onChange={id=>change('avatar_asset_id',id)}/><a className="button" href="/marketplace">{t('page.marketplace')} ↗</a></aside></div>
 {page&&<><section className="card module-form"><h2>{t('page.offerings')}</h2><div className="provider-editor"><form onSubmit={e=>{e.preventDefault();void saveOffer();}} className="module-form">
 <label>{t('title')}<input required minLength={2} maxLength={140} value={offer.title} onChange={e=>setOffer({...offer,title:e.target.value})}/></label>
 <label>{t('body')}<textarea rows={3} maxLength={3000} value={offer.description} onChange={e=>setOffer({...offer,description:e.target.value})}/></label>
 <label>{t('page.kind')}<select value={offer.kind} onChange={e=>setOffer({...offer,kind:e.target.value})}>{(['SERVICE','PRODUCT','RENTAL','EXPERIENCE'] as const).map(k=><option key={k} value={k}>{t(`page.${k.toLowerCase()}` as 'page.service')}</option>)}</select></label>
 <label>{t('page.price')}<input type="number" min={0} max={9999999999} step="0.01" required value={offer.price} onChange={e=>setOffer({...offer,price:Number(e.target.value)})}/></label>
 <label><input type="checkbox" checked={offer.status==='ACTIVE'} onChange={e=>setOffer({...offer,status:e.target.checked?'ACTIVE':'DRAFT'})}/>{t('page.active')}</label><button className="button primary" disabled={busy}>{t('page.add')}</button>{editId&&<button type="button" className="button" onClick={()=>{setEditId(null);setOffer(blankOffering);}}>{t('cancel')}</button>}
 </form><ImageInput label={t('page.cover')} value={offer.image_asset_id} onChange={id=>setOffer({...offer,image_asset_id:id})}/></div>
 {offers.map(o=><div className="list-row" key={o.id}><div><b>{o.title}</b><p>{o.price} {o.currency} · {o.status}</p></div><button className="button" onClick={()=>{setEditId(o.id);setOffer(o);}}>{t('page.edit')}</button></div>)}
 </section><section className="card"><h2>{t('page.inquiries')}</h2>{!inquiries.length&&<p>{t('empty')}</p>}{inquiries.map(i=><article className="inquiry-row" key={i.id}><p className="preserve-lines">{i.message}</p><small>{new Date(i.created_at).toLocaleString()}</small><form className="module-form" onSubmit={e=>{e.preventDefault();const reply=String(new FormData(e.currentTarget).get('reply')||'');void run(async()=>{const r=await supabase.from('provider_inquiries').update({reply,status:'CONTACTED'}).eq('id',i.id).select('id').single();if(r.error)throw r.error;setInquiries(x=>x.map(a=>a.id===i.id?{...a,reply,status:'CONTACTED'}:a));});}}><label>{t('page.reply')}<textarea name="reply" rows={3} required maxLength={3000} defaultValue={i.reply}/></label><button className="button" disabled={busy}>{t('page.sendReply')}</button></form><select aria-label={t('page.status')} disabled={busy} value={i.status} onChange={e=>{const status=e.target.value;void run(async()=>{const r=await supabase.from('provider_inquiries').update({status}).eq('id',i.id).select('id').single();if(r.error)throw r.error;setInquiries(x=>x.map(a=>a.id===i.id?{...a,status}:a));});}}><option value="NEW">{t('page.newStatus')}</option><option value="CONTACTED">{t('page.contactStatus')}</option><option value="CLOSED">{t('page.closed')}</option></select></article>)}</section></>}
 </>;
}
