'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {LanguageSwitch,useLocale} from '@/modules/localization/ui/provider';
import {type ProviderPage,type Offering,mediaUrl} from '../application/catalog';
import {Visual} from './visual';
export default function PublicProvider({page,offerings}:{page:ProviderPage;offerings:Offering[]}){
 const {t,locale}=useLocale();const [offeringId,setOfferingId]=useState('');const [message,setMessage]=useState('');const [quantity,setQuantity]=useState(1);const [location,setLocation]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [details,setDetails]=useState<Record<string,{label:string;value:unknown;unit?:string|null}[]>>({});const [variants,setVariants]=useState<Record<string,{id:string;title:string;price_delta:number;stock_quantity:number|null}[]>>({});
 useEffect(()=>{const ids=offerings.map(o=>o.id);if(!ids.length)return;Promise.all([supabase.from('provider_offering_attribute_values').select('offering_id,value,provider_attribute_definitions(label,unit)').in('offering_id',ids),supabase.from('provider_offering_variants').select('id,offering_id,title,price_delta,stock_quantity').in('offering_id',ids).eq('status','ACTIVE')]).then(([a,v])=>{if(a.data){const grouped:typeof details={};for(const row of a.data as any[]){const d=Array.isArray(row.provider_attribute_definitions)?row.provider_attribute_definitions[0]:row.provider_attribute_definitions;(grouped[row.offering_id]||=[]).push({label:d?.label||'Attribute',value:row.value,unit:d?.unit})}setDetails(grouped)}if(v.data){const grouped:typeof variants={};for(const row of v.data as any[])(grouped[row.offering_id]||=[]).push(row);setVariants(grouped)}})},[offerings]);
 async function send(){setBusy(true);setNotice('');setError('');try{const {data}=await supabase.auth.getUser();if(!data.user)throw new Error(t('signin'));if(offeringId){const result=await supabase.rpc('create_provider_order',{p_offering:offeringId,p_quantity:quantity,p_requirements:message,p_location:location,p_starts_at:null,p_ends_at:null});if(result.error)throw result.error;setNotice('Order request sent. Track the quote in My Cuelance.');}else{const result=await supabase.from('provider_inquiries').insert({provider_id:page.id,offering_id:null,requester_user_id:data.user.id,message});if(result.error)throw result.error;setNotice(t('page.sent'));}setMessage('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="public-site"><header className="public-nav"><a className="brand" href="/">CUE<span>LANCE</span></a><nav><a href="/marketplace">{t('page.marketplace')}</a><a href="/workspace">{t('page.dashboard')}</a><LanguageSwitch/></nav></header>
 <main><section className="provider-hero"><Visual src={mediaUrl(page.cover_asset_id)} alt={page.display_name}/><div className="hero-shade"/><div className="provider-hero-content"><p className="eyebrow">{t(`page.${page.role}`)} · {page.city}</p><h1>{page.display_name}</h1><p>{page.headline}</p><a className="button primary" href="#inquiry">{t('page.contact')} ↗</a></div></section>
 <div className="public-body"><section className="provider-about"><Visual src={mediaUrl(page.avatar_asset_id)} alt={page.display_name} className="provider-avatar"/><div><h2>{t('page.bio')}</h2><p className="preserve-lines">{page.bio}</p>{page.website&&<a className="button" href={page.website} target="_blank" rel="noopener noreferrer">{t('page.website')} ↗</a>}</div></section>
 <section><div className="section-heading"><h2>{t('page.offerings')}</h2><span>{offerings.length}</span></div><div className="visual-grid">{offerings.map(o=><article className="visual-card" key={o.id}><Visual src={mediaUrl(o.image_asset_id||page.cover_asset_id)} alt={o.title}/><div className="visual-card-body"><span className="eyebrow">{t(`page.${o.kind.toLowerCase()}` as 'page.service')} · {o.pricing_model||'FIXED'}</span><h3>{o.title}</h3><p>{o.description}</p><b>{o.pricing_model==='QUOTE'?'Request quote':`${t('page.from')} ${new Intl.NumberFormat(locale,{style:'currency',currency:o.currency}).format(o.price)}`}</b>{details[o.id]?.length>0&&<dl>{details[o.id].map((d,i)=><div key={i}><dt>{d.label}</dt><dd>{Array.isArray(d.value)?d.value.join(', '):String(d.value)} {d.unit}</dd></div>)}</dl>}{variants[o.id]?.length>0&&<p>{variants[o.id].map(v=>`${v.title}${v.price_delta?` (${v.price_delta>0?'+':''}${v.price_delta})`:''}`).join(' · ')}</p>}<a className="button" href="#inquiry" onClick={()=>{setOfferingId(o.id);setQuantity(o.minimum_quantity||1)}}>{o.kind==='PRODUCT'?'Order':'Request quote'} ↗</a></div></article>)}</div>{!offerings.length&&<p>{t('empty')}</p>}</section>
 <section className="card inquiry-form" id="inquiry"><h2>{offeringId?'Order or quote request':t('page.contact')}</h2><p>{t('page.requestHelp')}</p><form onSubmit={e=>{e.preventDefault();void send();}} className="module-form"><label>{t('page.offerings')}<select value={offeringId} onChange={e=>setOfferingId(e.target.value)}><option value="">{t('page.contact')}</option>{offerings.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label>{offeringId&&<><label>Quantity<input type="number" min={1} max={1000} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Delivery or service location<input maxLength={500} value={location} onChange={e=>setLocation(e.target.value)}/></label></>}<label>{t('body')}<textarea required minLength={10} maxLength={3000} rows={5} value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="button primary" disabled={busy}>{busy?t('working'):offeringId?'Submit order request':t('page.request')}</button></form>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error} <a href="/workspace">{t('page.dashboard')}</a></p>}</section></div></main></div>;
}
