'use client';
import {useState} from 'react';
import {supabase} from '@/lib/supabase';
import {LanguageSwitch,useLocale} from '@/modules/localization/ui/provider';
import {type ProviderPage,type Offering,mediaUrl} from '../application/catalog';
import {Visual} from './visual';
export default function PublicProvider({page,offerings}:{page:ProviderPage;offerings:Offering[]}){
 const {t,locale}=useLocale();const [offeringId,setOfferingId]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');
 async function send(){setBusy(true);setNotice('');setError('');try{const {data}=await supabase.auth.getUser();if(!data.user)throw new Error(t('signin'));const result=await supabase.from('provider_inquiries').insert({provider_id:page.id,offering_id:offeringId||null,requester_user_id:data.user.id,message});if(result.error)throw result.error;setMessage('');setNotice(t('page.sent'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="public-site"><header className="public-nav"><a className="brand" href="/">CUE<span>LANCE</span></a><nav><a href="/marketplace">{t('page.marketplace')}</a><a href="/workspace">{t('page.dashboard')}</a><LanguageSwitch/></nav></header>
 <main><section className="provider-hero"><Visual src={mediaUrl(page.cover_asset_id)} alt={page.display_name}/><div className="hero-shade"/><div className="provider-hero-content"><p className="eyebrow">{t(`page.${page.role}`)} · {page.city}</p><h1>{page.display_name}</h1><p>{page.headline}</p><a className="button primary" href="#inquiry">{t('page.contact')} ↗</a></div></section>
 <div className="public-body"><section className="provider-about"><Visual src={mediaUrl(page.avatar_asset_id)} alt={page.display_name} className="provider-avatar"/><div><h2>{t('page.bio')}</h2><p className="preserve-lines">{page.bio}</p>{page.website&&<a className="button" href={page.website} target="_blank" rel="noopener noreferrer">{t('page.website')} ↗</a>}</div></section>
 <section><div className="section-heading"><h2>{t('page.offerings')}</h2><span>{offerings.length}</span></div><div className="visual-grid">{offerings.map(o=><article className="visual-card" key={o.id}><Visual src={mediaUrl(o.image_asset_id||page.cover_asset_id)} alt={o.title}/><div className="visual-card-body"><span className="eyebrow">{t(`page.${o.kind.toLowerCase()}` as 'page.service')}</span><h3>{o.title}</h3><p>{o.description}</p><b>{t('page.from')} {new Intl.NumberFormat(locale,{style:'currency',currency:o.currency}).format(o.price)}</b><a className="button" href="#inquiry" onClick={()=>setOfferingId(o.id)}>{t('page.request')} ↗</a></div></article>)}</div>{!offerings.length&&<p>{t('empty')}</p>}</section>
 <section className="card inquiry-form" id="inquiry"><h2>{t('page.contact')}</h2><p>{t('page.requestHelp')}</p><form onSubmit={e=>{e.preventDefault();void send();}} className="module-form"><label>{t('page.offerings')}<select value={offeringId} onChange={e=>setOfferingId(e.target.value)}><option value="">{t('page.contact')}</option>{offerings.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label>{t('body')}<textarea required minLength={10} maxLength={3000} rows={5} value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="button primary" disabled={busy}>{busy?t('working'):t('page.request')}</button></form>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error} <a href="/workspace">{t('page.dashboard')}</a></p>}</section></div></main></div>;
}
