'use client';
import {useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useLocale,LanguageSwitch} from '@/modules/localization/ui/provider';
import {Visual} from '@/modules/providers/ui/visual';
type Event={id:string;title:string;description:string;banner_url:string|null;venue:string;city:string;address:string;starts_at:string;timezone:string;status:string};
type TicketType={id:string;name:string;description:string;price:number;currency:string;capacity:number;quantity_sold:number;status:string};
export default function PublicEvent({event,types}:{event:Event;types:TicketType[]}){const {t,locale}=useLocale();const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');
 async function reserve(id:string){setBusy(true);setError('');try{const {data}=await supabase.auth.getUser();if(!data.user?.email)throw new Error(t('signin'));const result=await supabase.rpc('reserve_ticket',{p_ticket_type:id,p_buyer_email:data.user.email});if(result.error)throw result.error;setNotice(t('event.issued'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="public-site"><header className="public-nav"><a href="/" className="brand">CUE<span>LANCE</span></a><nav><a href="/workspace?tab=wallet">{t('event.wallet')}</a><LanguageSwitch/></nav></header><main><section className="provider-hero event-hero"><Visual src={event.banner_url} alt={event.title}/><div className="hero-shade"/><div className="provider-hero-content"><p className="eyebrow">{event.city} / CUELANCE</p><h1>{event.title}</h1><p>{event.venue}</p><a href="#tickets" className="button primary">{t('event.tickets')} ↗</a></div></section><div className="public-body event-public-grid"><section><h2>{t('event.about')}</h2><p className="preserve-lines">{event.description}</p><dl className="event-facts"><dt>{t('event.date')}</dt><dd>{new Intl.DateTimeFormat(locale,{dateStyle:'full',timeStyle:'short',timeZone:event.timezone||'Asia/Riyadh'}).format(new Date(event.starts_at))} · {event.timezone}</dd><dt>{t('event.venue')}</dt><dd>{event.venue} · {event.address} · {event.city}</dd></dl></section><section id="tickets" className="card"><h2>{t('event.tickets')}</h2>{types.length===0&&<p>{t('empty')}</p>}{types.map(ticket=><article className="ticket-option" key={ticket.id}><h3>{ticket.name}</h3><p>{ticket.description}</p><b>{new Intl.NumberFormat(locale,{style:'currency',currency:ticket.currency}).format(ticket.price)}</b><button className="button primary" disabled={busy||Boolean(notice)||Number(ticket.price)>0||ticket.quantity_sold>=ticket.capacity} onClick={()=>reserve(ticket.id)}>{ticket.quantity_sold>=ticket.capacity?t('event.soldout'):Number(ticket.price)>0?t('event.paid'):t('event.free')}</button></article>)}{notice&&<p role="status">{notice} <a href="/workspace?tab=wallet">{t('event.wallet')}</a></p>}{error&&<p role="alert">{error} <a href="/workspace">{t('page.dashboard')}</a></p>}</section></div></main></div>;
}
