"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
import {ModuleHeading,Status} from "@/modules/ui/guided";
type Offer={id:string;title:string;counterparty_name:string;event_name:string;event_location:string;event_starts_at:string|null;fee:number;currency:string;status:string;artist_approval:string;terms:string};
type Contract={id:string;title:string;version:number;status:string;agency_signed_at:string|null;artist_signed_at:string|null};
type Calendar={id:string;title:string;kind:string;location:string;starts_at:string;ends_at:string;status:string};
export default function ArtistAgencyDesk(){const [offers,setOffers]=useState<Offer[]>([]);const [contracts,setContracts]=useState<Contract[]>([]);const [calendar,setCalendar]=useState<Calendar[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 async function load(){const [o,c,k]=await Promise.all([supabase.from("agency_offers").select("*").order("created_at",{ascending:false}),supabase.from("agency_contracts").select("*").order("created_at",{ascending:false}),supabase.from("agency_calendar_items").select("*").order("starts_at")]);const failed=[o,c,k].find(x=>x.error);if(failed?.error)setError(failed.error.message);else{setOffers(o.data||[]);setContracts(c.data||[]);setCalendar(k.data||[])}}
 useEffect(()=>{void load()},[]);async function rpc(name:string,args:Record<string,unknown>){const r=await supabase.rpc(name,args);if(r.error)setError(r.error.message);else{setError("");setNotice("Agency workflow updated");await load()}}
 return <section className="card"><ModuleHeading title="My agency deals" help="Review representation holds, approve offers, sign contracts and keep every decision visible."/><Status text={error} error/><Status text={notice}/><h3>Offers awaiting you</h3>{!offers.length&&<p>No connected agency offers.</p>}{offers.map(o=><article className="inquiry-row" key={o.id}><div className="card-title"><div><b>{o.title}</b><small>{o.counterparty_name} · {o.event_name}</small></div><span className="pill">{o.status}</span></div><p>{o.currency} {o.fee} · artist {o.artist_approval.toLowerCase()}</p><p>{o.terms}</p>{["SENT","NEGOTIATING","ACCEPTED"].includes(o.status)&&o.artist_approval==="PENDING"&&<div className="row-actions"><button className="button primary small" onClick={()=>rpc("agency_artist_offer_response",{p_offer:o.id,p_approved:true,p_note:"Approved by artist"})}>Approve offer</button><button className="button small" onClick={()=>rpc("agency_artist_offer_response",{p_offer:o.id,p_approved:false,p_note:"Declined by artist"})}>Decline</button></div>}</article>)}<h3>Contracts</h3>{contracts.map(c=><article className="inquiry-row" key={c.id}><div className="card-title"><b>{c.title} · v{c.version}</b><span className="pill">{c.status}</span></div><small>Agency {c.agency_signed_at?"signed":"pending"} · Artist {c.artist_signed_at?"signed":"pending"}</small>{["SENT","PARTIALLY_SIGNED"].includes(c.status)&&!c.artist_signed_at&&<button className="button primary small" onClick={()=>rpc("agency_sign_contract",{p_contract:c.id,p_as:"ARTIST"})}>Artist sign</button>}</article>)}<h3>Representation calendar</h3>{calendar.map(c=><article className="inquiry-row" key={c.id}><div className="card-title"><b>{c.title}</b><span className="pill">{c.status}</span></div><p>{c.kind} · {c.location}</p><small>{new Date(c.starts_at).toLocaleString()} → {new Date(c.ends_at).toLocaleString()}</small></article>)}</section>}
