"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { Help } from "@/modules/ui/guided";

export type EpkSectionContent = { heading?: string; text?: string; asset_ids?: string[]; links?: { label: string; url: string }[]; facts?: { label: string; value: string }[] };
export type EditableEpkSection = { id: string; type: string; enabled: boolean; visibility: string; sort_order: number; content_json?: EpkSectionContent };
type Definition = { title: string; help: string; text: string; facts?: string[]; links?: string };
const definitions: Record<string, Definition> = {
  hero:{title:"Hero and positioning",help:"The opening statement promoters see first. Manage the main artist image in Media and Artist profile.",text:"A concise positioning statement, residency or current campaign.",facts:["Based in","Available for","Languages"]},
  bio:{title:"Biography",help:"Use a full promoter-ready narrative. The profile biography remains your short summary.",text:"Long biography, story, sound, influences and current direction.",facts:["Years active","Performance style","Travel markets"]},
  music:{title:"Music and releases",help:"Add active listening links and attach audio or artwork from Media.",text:"Introduce signature releases, mixes, labels and current sound.",links:"SoundCloud | https://...\nSpotify | https://...\nLatest mix | https://...",facts:["Latest release","Record label","Monthly listeners"]},
  video:{title:"Performance video",help:"Add public YouTube, Vimeo or performance links.",text:"Describe the performance, venue and why the video matters.",links:"Live set | https://...\nShowreel | https://...",facts:["Filmed at","Set length"]},
  gallery:{title:"Press gallery",help:"Attach high-resolution public images from Media and record usage credits.",text:"Image credits, approved usage and photography notes.",facts:["Photographer","Usage rights","Credit line"]},
  highlights:{title:"Career highlights",help:"Lead with specific, verifiable achievements that help a buyer decide.",text:"One highlight per line: festivals, support slots, residencies, awards and milestones.",facts:["Headline show","Festival","Residency"]},
  press:{title:"Press and testimonials",help:"Include source names and active links; keep quotations short and attributed.",text:"Press summary, selected testimonials and notable coverage.",links:"Publication / feature | https://...",facts:["Publication","Radio","Award"]},
  events:{title:"Selected events",help:"Show rooms and audiences relevant to the bookings you want.",text:"Past and upcoming events, dates, cities and billing position.",facts:["Typical capacity","Recent city","Upcoming date"]},
  social:{title:"Social and audience",help:"Add public channels and useful audience context.",text:"Audience profile, territories and engagement context.",links:"Instagram | https://...\nTikTok | https://...\nYouTube | https://...",facts:["Instagram","TikTok","Top territory"]},
  downloads:{title:"Downloads",help:"Attach logos, press images, biographies and stage files from Media.",text:"Explain what is included and any usage restrictions.",links:"External press folder | https://...",facts:["Logo formats","Photo resolution","Updated"]},
  technical_rider:{title:"Technical and hospitality rider",help:"Be precise and practical. Attach a downloadable signed rider from Media when required.",text:"Critical notes, acceptable substitutions, advance deadline and safety requirements.",facts:["Performance setup","Preferred mixer","Players / decks","Turntables","Booth monitors","Microphones","DJ booth / stage","Power","Audio connections","Soundcheck","Set duration","Changeover","Hospitality","Local transport","Flights","Accommodation","Guest list","Technical contact","Tour manager","Emergency contact"]},
  booking:{title:"Booking and representation",help:"Give promoters the details required before submitting the booking form.",text:"Booking policy, response time, deal types and important conditions.",links:"Agency | https://...",facts:["Booking contact","Email","Phone","Response time","Fee guidance","Deposit","Cancellation"]},
  custom_content:{title:"Custom section",help:"Use this for content unique to your artist project.",text:"Custom content.",facts:["Detail","Detail","Detail"]},
};
const lines=(value:string)=>value.split("\n").map((line)=>line.trim()).filter(Boolean);
const pairs=(value:string)=>lines(value).map((line)=>{const [label,...rest]=line.split("|");return {label:label.trim(),value:rest.join("|").trim()}}).filter((item)=>item.label&&item.value);

export default function EpkSectionEditor({sections,onSaved}:{sections:EditableEpkSection[];onSaved:()=>void}){
 return <section className="epk-content-editor"><header className="card-title"><div><p className="eyebrow">CONTENT ARCHITECTURE</p><h2>Build the complete press kit</h2></div><span>{sections.length} sections</span></header><div className="epk-editor-list">{sections.map((section)=><SectionForm key={section.id} section={section} onSaved={onSaved}/>)}</div></section>
}
function SectionForm({section,onSaved}:{section:EditableEpkSection;onSaved:()=>void}){
 const definition=definitions[section.type]||definitions.custom_content;
 const [heading,setHeading]=useState("");const [text,setText]=useState("");const [facts,setFacts]=useState("");const [links,setLinks]=useState("");const [visibility,setVisibility]=useState("PUBLIC");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
 useEffect(()=>{setHeading(section.content_json?.heading||definition.title);setText(section.content_json?.text||"");setFacts((section.content_json?.facts||[]).map((item)=>`${item.label} | ${item.value}`).join("\n"));setLinks((section.content_json?.links||[]).map((item)=>`${item.label} | ${item.url}`).join("\n"));setVisibility(section.visibility||"PUBLIC")},[section,definition.title]);
 async function save(){const parsedLinks=pairs(links).map((item)=>({label:item.label,url:item.value}));if(parsedLinks.some((item)=>!/^https:\/\//i.test(item.url))){setNotice("Every link must use https://");return}setBusy(true);setNotice("");const content:EpkSectionContent={...section.content_json,heading:heading.trim(),text:text.trim(),facts:pairs(facts),links:parsedLinks};const {error}=await supabase.from("epk_sections").update({content_json:content,visibility,enabled:true}).eq("id",section.id);setBusy(false);setNotice(error?error.message:"Section saved and enabled.");if(!error)onSaved()}
 return <details className="card epk-editor-card" open={section.type==="technical_rider"}><summary><span><i className={section.enabled?"dot active":"dot"}/>{definition.title}</span><small>{section.enabled?"Active":"Draft"}</small></summary><div className="epk-editor-fields"><p className="helper">{definition.help}</p><label>Section heading <Help text="This heading appears in the live EPK and generated PDF."/><input maxLength={140} value={heading} onChange={(event)=>setHeading(event.target.value)}/></label><label>Editorial content <Help text={definition.text}/><textarea rows={6} maxLength={10000} value={text} placeholder={definition.text} onChange={(event)=>setText(event.target.value)}/></label>{definition.facts&&<label>Structured details <Help text="Use one item per line in Label | Value format. Blank values are ignored."/><textarea rows={Math.min(10,Math.max(4,definition.facts.length))} value={facts} placeholder={definition.facts.map((label)=>`${label} |`).join("\n")} onChange={(event)=>setFacts(event.target.value)}/></label>}{definition.links&&<label>Active links <Help text="Use one link per line in Label | https://... format."/><textarea rows={4} value={links} placeholder={definition.links} onChange={(event)=>setLinks(event.target.value)}/></label>}<label>Visibility<select value={visibility} onChange={(event)=>setVisibility(event.target.value)}><option value="PUBLIC">Public EPK and PDF</option><option value="PRIVATE">Private draft only</option></select></label><div className="row-actions"><button className="button primary" type="button" disabled={busy} onClick={save}>{busy?"Saving...":"Save section"}</button><span className="helper" role="status">{notice}</span></div></div></details>
}
