"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { Help, ModuleHeading, Status } from "@/modules/ui/guided";

type Snapshot={plan:string;name:string;status:string;period_end:string|null;entitlements:Record<string,boolean|number|string>;usage:Record<string,number>};
type Plan={code:string;name:string;audience:string;monthly_price:number;currency:string;entitlements:Record<string,boolean|number|string>};
const labels:Record<string,string>={"epk.templates":"EPK templates","epk.publications":"Publication versions","ai.daily":"AI requests per day","storage.mb":"Storage (MB)","organizations.max":"Organizations","team.max":"Team members","marketplace.apply":"Marketplace applications","marketplace.publish":"Opportunity publishing","communities.enabled":"Communities","ticketing.enabled":"Ticketing","analytics.level":"Analytics","custom_domain":"Custom domain"};
export default function PlanAccess({organizationId}:{organizationId?:string}){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [plans,setPlans]=useState<Plan[]>([]);const [error,setError]=useState("");
 useEffect(()=>{let live=true;Promise.all([supabase.rpc("entitlement_snapshot",{p_organization:organizationId||null}),supabase.from("plans").select("code,name,audience,monthly_price,currency,entitlements").eq("active",true).order("sort_order")]).then(([access,catalog])=>{if(!live)return;if(access.error)setError(access.error.message);else setSnapshot(access.data as Snapshot);if(catalog.error)setError(catalog.error.message);else setPlans((catalog.data||[]) as Plan[])});return()=>{live=false}},[organizationId]);
 if(error)return <><ModuleHeading title="Plan & access" help="Your plan is enforced by the Cuelance backend."/><Status text={error} error/></>;
 if(!snapshot)return <><ModuleHeading title="Plan & access" help="Loading your current access and usage..."/><div className="card skeleton-line"/></>;
 return <><ModuleHeading title="Plan & access" help="This is the server-authoritative access record for the selected account or organization."/><section className="plan-current"><div><p className="eyebrow">CURRENT PLAN</p><h2>{snapshot.name}</h2><p>{snapshot.status}{snapshot.period_end?` · renews ${new Date(snapshot.period_end).toLocaleDateString()}`:" · no billing connected"}</p></div><span className="pill">{snapshot.plan}</span></section><div className="entitlement-grid">{Object.entries(snapshot.entitlements).map(([key,value])=><article className="card entitlement-item" key={key}><div><b>{labels[key]||key}</b><Help text="This value comes from the active plan plus any time-limited administrator override."/></div><strong>{typeof value==="boolean"?(value?"Included":"Not included"):String(value)}</strong>{key==="ai.daily"&&<small>{snapshot.usage["ai.today"]||0} used today</small>}</article>)}</div><header className="section-heading"><div><p className="eyebrow">PLAN CATALOG</p><h2>Choose the operating level you need</h2></div></header><div className="plan-grid">{plans.map((plan)=><article className={`card plan-card ${plan.code===snapshot.plan?"active":""}`} key={plan.code}><span className="eyebrow">{plan.audience}</span><h3>{plan.name}</h3><strong>{Number(plan.monthly_price)===0?"Free":new Intl.NumberFormat("en-SA",{style:"currency",currency:plan.currency,maximumFractionDigits:0}).format(plan.monthly_price)+" / month"}</strong><ul>{Object.entries(plan.entitlements).slice(0,7).map(([key,value])=><li key={key}><span>{labels[key]||key}</span><b>{typeof value==="boolean"?(value?"Yes":"No"):String(value)}</b></li>)}</ul><button className="button full" disabled>{plan.code===snapshot.plan?"Current plan":"Checkout pending payment provider"}</button></article>)}</div><div className="module-note">Plan changes are intentionally admin-controlled until the verified payment adapter is connected. Existing workflows continue on Cuelance Free without losing data.</div></>;
}
