"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { Help, ModuleHeading, Status } from "@/modules/ui/guided";
import { api } from "@/lib/api-client";

type Snapshot={plan:string;name:string;status:string;period_end:string|null;entitlements:Record<string,boolean|number|string>;usage:Record<string,number>};
type Plan={code:string;name:string;audience:string;monthly_price:number;currency:string;entitlements:Record<string,boolean|number|string>};
const labels:Record<string,string>={"epk.templates":"EPK templates","epk.publications":"Publication versions","ai.daily":"AI requests per day","storage.mb":"Storage (MB)","organizations.max":"Organizations","team.max":"Team members","marketplace.apply":"Marketplace applications","marketplace.publish":"Opportunity publishing","communities.enabled":"Communities","ticketing.enabled":"Ticketing","analytics.level":"Analytics","custom_domain":"Custom domain"};
export default function PlanAccess({organizationId}:{organizationId?:string}){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [plans,setPlans]=useState<Plan[]>([]);const [error,setError]=useState("");
 const [payment,setPayment]=useState<{enabled:boolean;provider:string|null}>({enabled:false,provider:null});const [busy,setBusy]=useState("");
 useEffect(()=>{let live=true;Promise.all([supabase.rpc("entitlement_snapshot",{p_organization:organizationId||null}),supabase.from("plans").select("code,name,audience,monthly_price,currency,entitlements").eq("active",true).order("sort_order"),fetch("/api/v1/payments/status",{cache:"no-store"}).then(r=>r.json())]).then(([access,catalog,paymentStatus])=>{if(!live)return;if(access.error)setError(access.error.message);else setSnapshot(access.data as Snapshot);if(catalog.error)setError(catalog.error.message);else setPlans((catalog.data||[]) as Plan[]);setPayment(paymentStatus)});return()=>{live=false}},[organizationId]);
 useEffect(()=>{const providerOrderId=new URLSearchParams(window.location.search).get("token");if(!providerOrderId||sessionStorage.getItem(`captured:${providerOrderId}`))return;setBusy("capture");api<{completed:boolean}>("/api/v1/payments/paypal/capture",{providerOrderId}).then(()=>{sessionStorage.setItem(`captured:${providerOrderId}`,"1");window.history.replaceState({},"","/workspace?payment=success");window.location.reload()}).catch(e=>{setError(e instanceof Error?e.message:"Payment capture failed");setBusy("")})},[]);
 async function checkout(plan:Plan){try{setError("");setBusy(plan.code);const result=await api<{approvalUrl:string}>("/api/v1/payments/subscriptions/checkout",{plan:plan.code,organizationId:plan.audience==="ORGANIZATION"?organizationId||null:null,idempotencyKey:crypto.randomUUID(),returnPath:"/workspace?payment=success"});window.location.assign(result.approvalUrl)}catch(e){setError(e instanceof Error?e.message:"Checkout failed");setBusy("")}}
 if(error)return <><ModuleHeading title="Plan & access" help="Your plan is enforced by the Cuelance backend."/><Status text={error} error/></>;
 if(!snapshot)return <><ModuleHeading title="Plan & access" help="Loading your current access and usage..."/><div className="card skeleton-line"/></>;
 return <><ModuleHeading title="Plan & access" help="This is the server-authoritative access record for the selected account or organization."/>{busy==="capture"&&<Status text="Confirming your verified payment…"/>}<section className="plan-current"><div><p className="eyebrow">CURRENT PLAN</p><h2>{snapshot.name}</h2><p>{snapshot.status}{snapshot.period_end?` · renews ${new Date(snapshot.period_end).toLocaleDateString()}`:" · no billing connected"}</p></div><span className="pill">{snapshot.plan}</span></section><div className="entitlement-grid">{Object.entries(snapshot.entitlements).map(([key,value])=><article className="card entitlement-item" key={key}><div><b>{labels[key]||key}</b><Help text="This value comes from the active plan plus any time-limited administrator override."/></div><strong>{typeof value==="boolean"?(value?"Included":"Not included"):String(value)}</strong>{key==="ai.daily"&&<small>{snapshot.usage["ai.today"]||0} used today</small>}</article>)}</div><header className="section-heading"><div><p className="eyebrow">PLAN CATALOG</p><h2>Choose the operating level you need</h2></div></header><div className="plan-grid">{plans.map((plan)=>{const needsOrg=plan.audience==="ORGANIZATION"&&!organizationId;const disabled=plan.code===snapshot.plan||Number(plan.monthly_price)===0||!payment.enabled||needsOrg||Boolean(busy);return <article className={`card plan-card ${plan.code===snapshot.plan?"active":""}`} key={plan.code}><span className="eyebrow">{plan.audience}</span><h3>{plan.name}</h3><strong>{Number(plan.monthly_price)===0?"Free":new Intl.NumberFormat("en-SA",{style:"currency",currency:plan.currency,maximumFractionDigits:0}).format(plan.monthly_price)+" / month"}</strong><ul>{Object.entries(plan.entitlements).slice(0,7).map(([key,value])=><li key={key}><span>{labels[key]||key}</span><b>{typeof value==="boolean"?(value?"Yes":"No"):String(value)}</b></li>)}</ul><button className="button full" disabled={disabled} onClick={()=>checkout(plan)}>{plan.code===snapshot.plan?"Current plan":busy===plan.code?"Opening secure checkout…":needsOrg?"Select an organization":payment.enabled?`Continue with ${payment.provider}`:"Checkout setup pending"}</button></article>})}</div><div className="module-note">Payments use a provider-neutral Cuelance ledger. A plan activates only after Cuelance verifies the provider response, amount and currency; browser redirects alone never grant access.</div></>;
}
