"use client";
import { useLocale } from "./provider";
const ar: Record<string, string> = {
  "THE OPERATING SYSTEM FOR LIVE MUSIC": "منصة إدارة الموسيقى الحية",
  "Build your": "ابنِ",
  "career.": "مسيرتك.",
  "Run the": "أدر",
  "room.": "المشهد.",
  "Artist EPKs, booking discovery, promoter operations, communities and controlled entry—one connected platform.":
    "ملفات الفنانين والحجوزات وإدارة المروجين والمجتمعات والدخول في منصة متصلة.",
  "Artist → opportunity → event → ticket → secure entry":
    "فنان ← فرصة ← فعالية ← تذكرة ← دخول آمن",
  "ACCESS CUELANCE": "الدخول إلى كيولانس",
  Email: "البريد الإلكتروني",
  Password: "كلمة المرور",
  "Welcome back": "مرحباً بعودتك",
  "Create your account": "أنشئ حسابك",
  "Sign in": "تسجيل الدخول",
  "Create account": "إنشاء حساب",
  "Working…": "جارٍ التنفيذ…",
  "Resend verification email": "إعادة إرسال رسالة التحقق",
  "New here? Create an account": "جديد هنا؟ أنشئ حساباً",
  "Already have an account? Sign in": "لديك حساب؟ سجل الدخول",
  "? Guide": "؟ الدليل",
  "Live backend": "متصل",
  "Sign out": "تسجيل الخروج",
  "CUELANCE WORKSPACE": "مساحة عمل كيولانس",
  "CAREER + OPERATIONS": "المسيرة والإدارة",
  "This is one operational record—not a collection of disconnected tools.":
    "ملف موحد يربط مسيرتك بأعمالك.",
  "Artist profile": "ملف الفنان",
  "Published EPK": "الملف الصحفي المنشور",
  Applications: "الطلبات",
  Bookings: "الحجوزات",
  "Your live events": "فعالياتك المباشرة",
  Pipeline: "مسار الطلبات",
  "Live data": "بيانات مباشرة",
  "No applications yet": "لا توجد طلبات بعد",
  "NEXT BEST MOVE": "الخطوة التالية",
  "A platform becomes valuable when each record leads to the next operational action.":
    "انتقل من كل سجل إلى الخطوة التالية في عملك.",
  "Continue setup": "متابعة الإعداد",
  "ARTIST MODULE": "الفنان",
  "Own the professional record.": "أنشئ هويتك المهنية.",
  "Your reusable artist data powers the public EPK, marketplace search, booking and event lineups.":
    "تُستخدم بيانات الفنان في الملف الصحفي والبحث والحجز وبرامج الفعاليات.",
  "Stage name": "الاسم الفني",
  "e.g. Motata": "مثال: موتاتا",
  "Primary genre": "النوع الموسيقي الأساسي",
  "Primary city": "المدينة الأساسية",
  Country: "الدولة",
  "Short professional bio": "نبذة مهنية قصيرة",
  "Arabic biography": "النبذة العربية",
  "Arabic stage name": "الاسم الفني بالعربية",
  "The concise story promoters should understand in 15 seconds.":
    "قصة موجزة يفهمها المروج خلال 15 ثانية.",
  "Profile ownership is enforced by the database: an artist cannot edit another DJ’s record.":
    "تحمي قاعدة البيانات ملكية الملف، فلا يستطيع فنان تعديل ملف فنان آخر.",
  "EPK MODULE": "الملف الصحفي",
  "EPK studio": "استوديو الملف الصحفي",
  "Content is stored separately from presentation, so templates can evolve without losing the artist record.":
    "يُحفظ المحتوى منفصلاً عن التصميم، فيمكن تغيير القالب دون فقد البيانات.",
  Sections: "الأقسام",
  active: "مفعّل",
  "Create the EPK": "إنشاء الملف الصحفي",
  "PUBLIC EPK": "الملف الصحفي العام",
  PRESENTATION: "التصميم",
  "Choose a template": "اختر قالباً",
  "Publish EPK": "نشر الملف الصحفي",
  "Open live EPK": "فتح الملف المنشور",
  "Publishing creates an immutable publication version in the database.":
    "ينشئ النشر نسخة محفوظة مستقلة في قاعدة البيانات.",
  "MARKETPLACE MODULE": "سوق الفرص",
  "Find the right rooms.": "اعثر على الفرصة المناسبة.",
  "Published opportunities are searchable and applications move through validated states.":
    "استعرض الفرص المنشورة وتابع حالات طلباتك.",
  "All genres": "كل الأنواع",
  "Saudi Arabia": "السعودية",
  "Available dates": "المواعيد المتاحة",
  "Verified promoters": "مروجون موثقون",
  "No published opportunities": "لا توجد فرص منشورة",
  "ORGANIZATIONS + MARKETPLACE": "المؤسسات والفرص",
  "Organizations separate promoters, venues, agencies and brands from individual creator accounts.":
    "تدير المؤسسات أعمال المروجين والأماكن والوكالات والعلامات التجارية.",
  "Organization name": "اسم المؤسسة",
  "e.g. After Dark Riyadh": "مثال: أفتر دارك الرياض",
  "Organization type": "نوع المؤسسة",
  "Create organization": "إنشاء مؤسسة",
  "PUBLISH OPPORTUNITY": "نشر فرصة",
  "Bring artists into the pipeline.": "استقبل طلبات الفنانين.",
  "Opportunity title": "عنوان الفرصة",
  "Riyadh warehouse closing set": "الفقرة الختامية في الرياض",
  Brief: "الملخص",
  "Set time, music direction, experience and selection criteria.":
    "وقت الفقرة والتوجه الموسيقي والخبرة ومعايير الاختيار.",
  "Event date": "تاريخ الفعالية",
  "Publish opportunity": "نشر الفرصة",
  "Your listings": "فرصك المنشورة",
  "No listings yet": "لا توجد فرص بعد",
  "EVENTS + TICKETING": "الفعاليات والتذاكر",
  "Build an event people can enter.": "أنشئ فعالية جاهزة لاستقبال الجمهور.",
  "Inventory, orders, tickets and entry are treated as one controlled workflow—not independent pages.":
    "تتكامل السعة والطلبات والتذاكر والدخول في مسار واحد.",
  "Organization required": "تحتاج إلى مؤسسة",
  "01 / EVENT": "٠١ / الفعالية",
  "Event title": "عنوان الفعالية",
  "After Dark — Opening Night": "أفتر دارك — ليلة الافتتاح",
  Venue: "المكان",
  "Venue or district": "المكان أو الحي",
  "Starts at": "موعد البداية",
  "Publish event": "نشر الفعالية",
  "02 / TICKET TYPE": "٠٢ / نوع التذكرة",
  Event: "الفعالية",
  "Select event": "اختر فعالية",
  "Ticket name": "اسم التذكرة",
  "Price (SAR)": "السعر (ريال)",
  Capacity: "السعة",
  "Ticket inventory": "مخزون التذاكر",
  "Transaction-protected": "محمي بالمعاملات",
  "Paid ticket checkout is intentionally disabled until Cuelance connects a verified payment provider. Complimentary tickets remain available and are issued as real credentials.":
    "الدفع معطل حتى ربط مزود دفع معتمد. التذاكر المجانية متاحة وتصدر باعتمادات فعلية.",
  "issued ·": "صادرة ·",
  "Issue complimentary ticket": "إصدار تذكرة مجانية",
  "Checkout pending provider": "الدفع بانتظار المزود",
  "No ticket types": "لا توجد أنواع تذاكر",
  "COMMUNITY MODULE": "المجتمع",
  "Turn attendance into a durable audience.":
    "ابنِ مجتمعاً يستمر بعد الفعالية.",
  "Members move through an explicit pending → active workflow under organization control.":
    "تُدار العضويات من قيد الانتظار إلى نشطة تحت إشراف المؤسسة.",
  "NEW COMMUNITY": "مجتمع جديد",
  "Build a member layer around your events.": "ابنِ مجتمع أعضاء حول فعالياتك.",
  "e.g. After Dark Residents": "مثال: أعضاء أفتر دارك",
  Create: "إنشاء",
  "Managed status:": "الحالة:",
  "Request membership": "طلب عضوية",
  "No communities yet": "لا توجد مجتمعات بعد",
  "Loading Cuelance EPK…": "جارٍ تحميل الملف الصحفي…",
  "EPK unavailable": "الملف الصحفي غير متاح",
  "Go to Cuelance": "انتقل إلى كيولانس",
  "Electronic press kit": "الملف الصحفي الإلكتروني",
  ABOUT: "نبذة",
  "Built for the room.": "موسيقى تناسب المشهد.",
  "EPK FORMAT": "قالب الملف الصحفي",
  "Languages:": "اللغات:",
  BOOKING: "الحجز",
  Bring: "استضف",
  "to your next room.": "في فعاليتك القادمة.",
  "Send a structured brief. It becomes a real booking record in the artist’s Cuelance workspace.":
    "أرسل ملخصاً منظماً ليظهر كطلب حجز في مساحة عمل الفنان.",
  Name: "الاسم",
  Organization: "المؤسسة",
  City: "المدينة",
  Budget: "الميزانية",
  "e.g. 6,000 SAR": "مثال: 6000 ريال",
  "Venue, audience, set time and what you need from the artist.":
    "المكان والجمهور ووقت الفقرة وما تحتاجه من الفنان.",
  "Published on Cuelance": "منشور على كيولانس",
  "Sending…": "جارٍ الإرسال…",
  "Send booking enquiry": "إرسال استفسار الحجز",
  "Save changes": "حفظ التغييرات",
  "Saving…": "جارٍ الحفظ…",
  "Create artist profile": "إنشاء ملف الفنان",
  "Save EPK draft": "حفظ مسودة الملف الصحفي",
  "Save draft": "حفظ المسودة",
  Applied: "تم التقديم",
  Apply: "تقديم",
  "Apply to opportunity": "التقدم للفرصة",
  "Create ticket type": "إنشاء نوع تذكرة",
  "Select an event": "اختر فعالية",
  "Artist ready": "الفنان جاهز",
  "Artist setup": "إعداد الفنان",
  "No organization yet": "لا توجد مؤسسة بعد",
  "Location TBC": "الموقع لاحقاً",
  "Date TBC": "التاريخ لاحقاً",
  "Your opportunity responses will land here with their current state.":
    "تظهر هنا طلباتك وحالاتها الحالية.",
  "Build the artist profile.": "أنشئ ملف الفنان.",
  "Create the first EPK.": "أنشئ أول ملف صحفي.",
  "Open your promoter organization.": "أنشئ مؤسسة المروج.",
  "Create an event and ticket type.": "أنشئ فعالية ونوع تذكرة.",
  "Community name": "اسم المجتمع",
  "Activate inventory": "تفعيل المخزون",
  "Create profile first": "أنشئ الملف أولاً",
  Hero: "الغلاف",
  Bio: "النبذة",
  Music: "الموسيقى",
  Video: "الفيديو",
  Gallery: "المعرض",
  Highlights: "أبرز الإنجازات",
  Press: "الصحافة",
  Events: "الفعاليات",
  Social: "التواصل",
  Downloads: "التنزيلات",
  "Technical rider": "المتطلبات التقنية",
  Booking: "الحجز",
  More: "المزيد",
  "Create an artist profile, then save your first EPK draft.":
    "أنشئ ملف الفنان ثم احفظ أول مسودة للملف الصحفي.",
  "Add your first ticket type above.": "أضف أول نوع تذكرة أعلاه.",
  "Create an organization in Promoter desk to manage events.":
    "أنشئ مؤسسة في مكتب المروج لإدارة الفعاليات.",
};
export function useLegacy() {
  const { locale } = useLocale();
  return (text: string) => (locale === "ar" ? ar[text] || text : text);
}
export function Localized({ text }: { text: string }) {
  const tr = useLegacy();
  return <>{tr(text)}</>;
}
